"""Seele Fallback-Fragen - Statische Fragen fuer alle nicht-auto-extrahierbaren Profil-Felder."""

# Fallback-Fragen decken alle 27 nicht-auto-extrahierbaren Felder ab.
# Werden verwendet wenn kein CV vorhanden oder AI-Generierung fehlschlaegt.
FALLBACK_FRAGEN = {
    "profil": [
        # -- Motivation (hoch) --
        {
            "key": "motivation.aktuelle_situation",
            "frage": "Was beschreibt deine aktuelle Situation am besten?",
            "typ": "chips",
            "optionen": [
                "Aktiv auf Jobsuche",
                "Offen für Neues",
                "Karrierewechsel",
                "Erster Job",
                "Wiedereinstieg",
            ],
            "mehrfach": False,
        },
        {
            "key": "motivation.wechselgrund",
            "frage": "Warum möchtest du wechseln?",
            "typ": "chips",
            "optionen": [
                "Bessere Perspektiven",
                "Neues Umfeld",
                "Mehr Gehalt",
                "Weiterentwicklung",
                "Unzufriedenheit",
                "Umzug",
            ],
            "mehrfach": False,
        },
        {
            "key": "motivation.wichtig_im_job",
            "frage": "Was ist dir im nächsten Job besonders wichtig?",
            "typ": "chips_freitext",
            "optionen": [
                "Work-Life-Balance",
                "Gehalt",
                "Teamkultur",
                "Weiterbildung",
                "Aufstiegschancen",
                "Sinnvolle Arbeit",
                "Flexibilität",
                "Technische Herausforderung",
            ],
            "mehrfach": True,
            "max_auswahl": 5,
        },
        {
            "key": "motivation.wechsel_tempo",
            "frage": "Wie schnell möchtest du wechseln?",
            "typ": "chips",
            "optionen": ["Sofort verfügbar", "In 1-3 Monaten", "Schaue mich nur um"],
            "mehrfach": False,
        },
        {
            "key": "motivation.karriereziel",
            "frage": "Was ist dein langfristiges Karriereziel?",
            "typ": "freitext",
            "optionen": None,
            "mehrfach": False,
        },
        {
            "key": "motivation.dealbreaker",
            "frage": "Was sind absolute No-Gos für dich bei einem Job?",
            "typ": "chips_freitext",
            "optionen": [
                "Überstunden-Kultur",
                "Kein Home-Office",
                "Schlechte Bezahlung",
                "Befristeter Vertrag",
                "Keine Weiterbildung",
                "Toxisches Umfeld",
            ],
            "mehrfach": True,
            "max_auswahl": 4,
        },
        {
            "key": "motivation.werte",
            "frage": "Welche Werte sind dir im Beruf wichtig?",
            "typ": "chips_freitext",
            "optionen": [
                "Nachhaltigkeit",
                "Innovation",
                "Teamgeist",
                "Ehrlichkeit",
                "Diversität",
                "Eigenverantwortung",
            ],
            "mehrfach": True,
            "max_auswahl": 4,
        },
        # -- Arbeitsstil (hoch/mittel) --
        {
            "key": "arbeitsstil.arbeitsmodell",
            "frage": "Welches Arbeitsmodell passt zu dir?",
            "typ": "chips",
            "optionen": ["Remote", "Hybrid", "Vor Ort", "Ist mir egal"],
            "mehrfach": True,
        },
        {
            "key": "arbeitsstil.staerken",
            "frage": "Welche Stärken würdest du dir zuschreiben?",
            "typ": "chips_freitext",
            "optionen": [
                "Analytisches Denken",
                "Kommunikation",
                "Problemlösung",
                "Teamarbeit",
                "Kreativität",
                "Organisationstalent",
                "Eigeninitiative",
                "Führungskompetenz",
            ],
            "mehrfach": True,
            "max_auswahl": 5,
        },
        {
            "key": "arbeitsstil.teamrolle",
            "frage": "Welche Rolle nimmst du in Teams ein?",
            "typ": "chips",
            "optionen": [
                "Teamleader",
                "Koordinator",
                "Ideengeber",
                "Umsetzer",
                "Vermittler",
                "Analyst",
            ],
            "mehrfach": False,
        },
        {
            "key": "arbeitsstil.typ",
            "frage": "Wie würdest du deinen Arbeitsstil beschreiben?",
            "typ": "chips",
            "optionen": [
                "Kreativ",
                "Analytisch",
                "Operativ",
                "Strategisch",
                "Kommunikativ",
                "Detailorientiert",
            ],
            "mehrfach": False,
        },
        {
            "key": "arbeitsstil.kommunikation",
            "frage": "Wie kommunizierst du am liebsten im Team?",
            "typ": "chips",
            "optionen": [
                "Persönliche Gespräche",
                "Video-Calls",
                "Chat/Slack",
                "E-Mail",
                "Async-first",
            ],
            "mehrfach": False,
        },
        {
            "key": "arbeitsstil.entwicklungsbereiche",
            "frage": "In welchen Bereichen möchtest du dich weiterentwickeln?",
            "typ": "chips_freitext",
            "optionen": [
                "Führungskompetenz",
                "Technische Skills",
                "Kommunikation",
                "Projektmanagement",
                "Fachliche Vertiefung",
                "Strategisches Denken",
            ],
            "mehrfach": True,
            "max_auswahl": 4,
        },
        # -- Gehalt (hoch/mittel) --
        {
            "key": "gehaltsvorstellung.wunsch",
            "frage": "In welchem Gehaltsbereich siehst du dich?",
            "typ": "slider",
            "optionen": None,
            "mehrfach": False,
            "min_wert": 25000,
            "max_wert": 150000,
            "schritt": 5000,
        },
        {
            "key": "gehaltsvorstellung.minimum",
            "frage": "Was ist dein absolutes Mindestgehalt (Jahresbrutto)?",
            "typ": "slider",
            "optionen": None,
            "mehrfach": False,
            "min_wert": 20000,
            "max_wert": 120000,
            "schritt": 5000,
        },
        {
            "key": "gehaltsvorstellung.benefits_wichtig",
            "frage": "Welche Benefits sind dir neben dem Gehalt wichtig?",
            "typ": "chips_freitext",
            "optionen": [
                "Home-Office",
                "Firmenwagen",
                "Weiterbildungsbudget",
                "Betriebliche Altersvorsorge",
                "Flexible Arbeitszeiten",
                "Jobticket",
            ],
            "mehrfach": True,
            "max_auswahl": 5,
        },
        {
            "key": "gehaltsvorstellung.verhandelbar",
            "frage": "Ist deine Gehaltsvorstellung verhandelbar?",
            "typ": "chips",
            "optionen": ["Ja, flexibel", "Etwas Spielraum", "Eher nicht", "Fest"],
            "mehrfach": False,
        },
        # -- Persoenliche Daten (hoch/mittel) --
        {
            "key": "persoenliche_daten.verfuegbar_ab",
            "frage": "Ab wann bist du verfügbar?",
            "typ": "chips",
            "optionen": ["Sofort", "In 1 Monat", "In 3 Monaten", "Ab einem bestimmten Datum"],
            "mehrfach": False,
        },
        {
            "key": "persoenliche_daten.umzugsbereit",
            "frage": "Wärst du bereit, für den richtigen Job umzuziehen?",
            "typ": "chips",
            "optionen": ["Ja", "Vielleicht", "Nein", "Nur innerhalb Deutschlands"],
            "mehrfach": False,
        },
        {
            "key": "persoenliche_daten.kuendigungsfrist",
            "frage": "Wie lang ist deine aktuelle Kündigungsfrist?",
            "typ": "chips",
            "optionen": [
                "Keine (nicht angestellt)",
                "2 Wochen",
                "1 Monat",
                "3 Monate",
                "6 Monate",
            ],
            "mehrfach": False,
        },
        # -- Berufserfahrung (mittel) --
        {
            "key": "berufserfahrung.fuehrungserfahrung",
            "frage": "Hast du Führungserfahrung?",
            "typ": "chips",
            "optionen": [
                "Keine",
                "Projektleitung",
                "Teamleitung (2-5 Personen)",
                "Abteilungsleitung (5+)",
                "C-Level / Geschäftsführung",
            ],
            "mehrfach": False,
        },
        # -- Persoenlichkeit (mittel/niedrig) --
        {
            "key": "persoenlichkeit.selbstbeschreibung",
            "frage": "Wie würdest du dich in 3 Worten beschreiben?",
            "typ": "freitext",
            "optionen": None,
            "mehrfach": False,
        },
        {
            "key": "persoenlichkeit.hobbys_relevant",
            "frage": "Hast du Hobbys die beruflich relevant sein könnten?",
            "typ": "chips_freitext",
            "optionen": [
                "Open Source",
                "Bloggen/Schreiben",
                "Ehrenamt",
                "Mentoring",
                "Sport/Fitness",
                "Netzwerken",
            ],
            "mehrfach": True,
            "max_auswahl": 4,
        },
        {
            "key": "persoenlichkeit.fun_fact",
            "frage": "Gibt es einen Fun Fact über dich?",
            "typ": "freitext",
            "optionen": None,
            "mehrfach": False,
        },
    ],
    # Backward-compat: alte Session-Typen verweisen auf profil
    "onboarding": None,  # wird dynamisch aufgelöst
    "pre_bewerbung": None,  # wird dynamisch aufgelöst
    "micro": [],
}
