"""Templates Blueprint - deprecated.

The template system has been removed. All cover letters are now
fully generated by AI. This blueprint only keeps the list-simple
endpoint for Chrome Extension backward compatibility.
"""

from flask import Blueprint, jsonify

templates_bp = Blueprint("templates", __name__)


@templates_bp.route("/list-simple", methods=["GET"])
def list_simple():
    """Return empty template list for extension backward compatibility."""
    return jsonify({"templates": []})
