"""Initial migration - all existing tables

Revision ID: 4119d07912f4
Revises: 
Create Date: 2026-01-14 16:06:19.606794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4119d07912f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchases_paypal_order_id'))
        batch_op.drop_index(batch_op.f('ix_purchases_status'))

    op.drop_table('purchases')
    with op.batch_alter_table('ats_analyses', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('email_accounts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('idx_email_accounts_user_id'))
        batch_op.create_index(batch_op.f('ix_email_accounts_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('interview_questions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('idx_interview_questions_application_id'))
        batch_op.create_index(batch_op.f('ix_interview_questions_application_id'), ['application_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'])

    with op.batch_alter_table('job_recommendations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('idx_job_recommendations_user_id'))
        batch_op.create_index(batch_op.f('ix_job_recommendations_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('job_requirements', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('idx_job_requirements_application_id'))
        batch_op.create_index(batch_op.f('ix_job_requirements_application_id'), ['application_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'])

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('plan',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('free', 'basic', 'pro', name='subscriptionplan'),
               existing_nullable=False,
               existing_server_default=sa.text("'free'"))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('active', 'canceled', 'past_due', 'trialing', name='subscriptionstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'active'"))
        batch_op.drop_index(batch_op.f('idx_subscriptions_stripe_customer_id'))
        batch_op.drop_index(batch_op.f('idx_subscriptions_stripe_subscription_id'))
        batch_op.drop_index(batch_op.f('idx_subscriptions_user_id'))
        batch_op.create_index(batch_op.f('ix_subscriptions_stripe_customer_id'), ['stripe_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_stripe_subscription_id'), ['stripe_subscription_id'], unique=True)

    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('idx_token_blacklist_jti'))
        batch_op.create_index(batch_op.f('ix_token_blacklist_jti'), ['jti'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_stripe_customer_id'))
        batch_op.create_index(batch_op.f('ix_users_stripe_customer_id'), ['stripe_customer_id'], unique=True)
        batch_op.drop_column('credits_remaining')
        batch_op.drop_column('total_credits_purchased')
        batch_op.drop_column('credits_max')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credits_max', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('total_credits_purchased', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('credits_remaining', sa.INTEGER(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_stripe_customer_id'))
        batch_op.create_index(batch_op.f('idx_users_stripe_customer_id'), ['stripe_customer_id'], unique=1)

    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blacklist_jti'))
        batch_op.create_index(batch_op.f('idx_token_blacklist_jti'), ['jti'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_stripe_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_stripe_customer_id'))
        batch_op.create_index(batch_op.f('idx_subscriptions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_subscriptions_stripe_subscription_id'), ['stripe_subscription_id'], unique=1)
        batch_op.create_index(batch_op.f('idx_subscriptions_stripe_customer_id'), ['stripe_customer_id'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('active', 'canceled', 'past_due', 'trialing', name='subscriptionstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('plan',
               existing_type=sa.Enum('free', 'basic', 'pro', name='subscriptionplan'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'free'"))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('job_requirements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_job_requirements_application_id'))
        batch_op.create_index(batch_op.f('idx_job_requirements_application_id'), ['application_id'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('job_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_recommendations_user_id'))
        batch_op.create_index(batch_op.f('idx_job_recommendations_user_id'), ['user_id'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('interview_questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_interview_questions_application_id'))
        batch_op.create_index(batch_op.f('idx_interview_questions_application_id'), ['application_id'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('email_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_accounts_user_id'))
        batch_op.create_index(batch_op.f('idx_email_accounts_user_id'), ['user_id'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('ats_analyses', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('purchases',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('package_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('credits_purchased', sa.INTEGER(), nullable=False),
    sa.Column('price_eur', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('paypal_order_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('paypal_payer_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('paypal_payer_email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchases_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_paypal_order_id'), ['paypal_order_id'], unique=1)

    # ### end Alembic commands ###
