"""add seele tables

Revision ID: 6d7e02aecd4d
Revises: 175d87d8f730
Create Date: 2026-02-22 03:09:46.626024

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6d7e02aecd4d"
down_revision = "175d87d8f730"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "seele_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("profil_json", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("vollstaendigkeit", sa.Integer(), nullable=False),
        sa.Column("erstellt_am", sa.DateTime(), nullable=True),
        sa.Column("aktualisiert_am", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("seele_profiles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_seele_profiles_user_id"), ["user_id"], unique=True)

    op.create_table(
        "seele_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("session_typ", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("fragen_geplant", sa.Integer(), nullable=False),
        sa.Column("fragen_beantwortet", sa.Integer(), nullable=False),
        sa.Column("fragen_uebersprungen", sa.Integer(), nullable=False),
        sa.Column("kontext_json", sa.Text(), nullable=True),
        sa.Column("gestartet_am", sa.DateTime(), nullable=True),
        sa.Column("beendet_am", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("seele_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_seele_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "seele_antworten",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("frage_key", sa.String(length=100), nullable=False),
        sa.Column("frage_text", sa.String(length=500), nullable=False),
        sa.Column("antwort_typ", sa.String(length=20), nullable=False),
        sa.Column("antwort_json", sa.Text(), nullable=True),
        sa.Column("uebersprungen", sa.Boolean(), nullable=False),
        sa.Column("beantwortet_am", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["seele_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("seele_antworten", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_seele_antworten_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_seele_antworten_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.alter_column(
            "plan",
            existing_type=sa.VARCHAR(length=5),
            type_=sa.Enum("free", "starter", "pro", name="subscriptionplan"),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.alter_column(
            "plan",
            existing_type=sa.Enum("free", "starter", "pro", name="subscriptionplan"),
            type_=sa.VARCHAR(length=5),
            existing_nullable=False,
        )

    with op.batch_alter_table("seele_antworten", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_seele_antworten_user_id"))
        batch_op.drop_index(batch_op.f("ix_seele_antworten_session_id"))

    op.drop_table("seele_antworten")
    with op.batch_alter_table("seele_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_seele_sessions_user_id"))

    op.drop_table("seele_sessions")
    with op.batch_alter_table("seele_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_seele_profiles_user_id"))

    op.drop_table("seele_profiles")
    # ### end Alembic commands ###
