"""add user job preferences

Revision ID: 77dfe5317514
Revises: b4c5d6e7f8a9
Create Date: 2026-02-17 18:17:13.867512

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "77dfe5317514"
down_revision = "b4c5d6e7f8a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("preferred_location", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("preferred_working_time", sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("preferred_working_time")
        batch_op.drop_column("preferred_location")

    # ### end Alembic commands ###
